require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DrillingStringsController do

  # This should return the minimal set of attributes required to create a valid
  # DrillingString. As you add validations to DrillingString, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DrillingStringsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all drilling_strings as @drilling_strings" do
      drilling_string = DrillingString.create! valid_attributes
      get :index, {}, valid_session
      assigns(:drilling_strings).should eq([drilling_string])
    end
  end

  describe "GET show" do
    it "assigns the requested drilling_string as @drilling_string" do
      drilling_string = DrillingString.create! valid_attributes
      get :show, {:id => drilling_string.to_param}, valid_session
      assigns(:drilling_string).should eq(drilling_string)
    end
  end

  describe "GET new" do
    it "assigns a new drilling_string as @drilling_string" do
      get :new, {}, valid_session
      assigns(:drilling_string).should be_a_new(DrillingString)
    end
  end

  describe "GET edit" do
    it "assigns the requested drilling_string as @drilling_string" do
      drilling_string = DrillingString.create! valid_attributes
      get :edit, {:id => drilling_string.to_param}, valid_session
      assigns(:drilling_string).should eq(drilling_string)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DrillingString" do
        expect {
          post :create, {:drilling_string => valid_attributes}, valid_session
        }.to change(DrillingString, :count).by(1)
      end

      it "assigns a newly created drilling_string as @drilling_string" do
        post :create, {:drilling_string => valid_attributes}, valid_session
        assigns(:drilling_string).should be_a(DrillingString)
        assigns(:drilling_string).should be_persisted
      end

      it "redirects to the created drilling_string" do
        post :create, {:drilling_string => valid_attributes}, valid_session
        response.should redirect_to(DrillingString.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved drilling_string as @drilling_string" do
        # Trigger the behavior that occurs when invalid params are submitted
        DrillingString.any_instance.stub(:save).and_return(false)
        post :create, {:drilling_string => {}}, valid_session
        assigns(:drilling_string).should be_a_new(DrillingString)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DrillingString.any_instance.stub(:save).and_return(false)
        post :create, {:drilling_string => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested drilling_string" do
        drilling_string = DrillingString.create! valid_attributes
        # Assuming there are no other drilling_strings in the database, this
        # specifies that the DrillingString created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DrillingString.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => drilling_string.to_param, :drilling_string => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested drilling_string as @drilling_string" do
        drilling_string = DrillingString.create! valid_attributes
        put :update, {:id => drilling_string.to_param, :drilling_string => valid_attributes}, valid_session
        assigns(:drilling_string).should eq(drilling_string)
      end

      it "redirects to the drilling_string" do
        drilling_string = DrillingString.create! valid_attributes
        put :update, {:id => drilling_string.to_param, :drilling_string => valid_attributes}, valid_session
        response.should redirect_to(drilling_string)
      end
    end

    describe "with invalid params" do
      it "assigns the drilling_string as @drilling_string" do
        drilling_string = DrillingString.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DrillingString.any_instance.stub(:save).and_return(false)
        put :update, {:id => drilling_string.to_param, :drilling_string => {}}, valid_session
        assigns(:drilling_string).should eq(drilling_string)
      end

      it "re-renders the 'edit' template" do
        drilling_string = DrillingString.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DrillingString.any_instance.stub(:save).and_return(false)
        put :update, {:id => drilling_string.to_param, :drilling_string => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested drilling_string" do
      drilling_string = DrillingString.create! valid_attributes
      expect {
        delete :destroy, {:id => drilling_string.to_param}, valid_session
      }.to change(DrillingString, :count).by(-1)
    end

    it "redirects to the drilling_strings list" do
      drilling_string = DrillingString.create! valid_attributes
      delete :destroy, {:id => drilling_string.to_param}, valid_session
      response.should redirect_to(drilling_strings_url)
    end
  end

end
